"""Init

Revision ID: 5f0bab36f9b1
Revises: 
Create Date: 2025-02-27 19:18:32.088413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from connectors.db.JsonDecorator import JsonDecorator

# revision identifiers, used by Alembic.
revision: str = '5f0bab36f9b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=255), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('md5sum', sa.String(length=255), nullable=False),
    sa.Column('clean', sa.Boolean(), nullable=False),
    sa.Column('duplicated_md5', sa.Boolean(), nullable=False),
    sa.Column('size', sa.BIGINT(), nullable=False),
    sa.Column('created', sa.BIGINT(), nullable=False),
    sa.Column('modified', sa.BIGINT(), nullable=False),
    sa.Column('date_created', sa.BIGINT(), nullable=True),
    sa.Column('exiftool_data', JsonDecorator.JsonDecorator(), nullable=False),
    sa.Column('File_FileModifyDate', sa.Text(), nullable=False),
    sa.Column('EXIF_ModifyDate', sa.Text(), nullable=False),
    sa.Column('EXIF_DateTimeOriginal', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=255), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('md5sum', sa.String(length=255), nullable=False),
    sa.Column('clean', sa.Boolean(), nullable=False),
    sa.Column('duplicated_md5', sa.Boolean(), nullable=False),
    sa.Column('size', sa.BIGINT(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('modified', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('files')
    # ### end Alembic commands ###
