"""Add-to-be-deleted and new_path_after_deleted

Revision ID: 6994f9aaf939
Revises: 5f0bab36f9b1
Create Date: 2025-02-28 17:55:56.484778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6994f9aaf939'
down_revision: Union[str, None] = '5f0bab36f9b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('to_be_deleted', sa.Boolean(), nullable=True, default=False))
    op.add_column('files', sa.Column('new_path_after_deleted', sa.Text(), nullable=True, default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'new_path_after_deleted')
    op.drop_column('files', 'to_be_deleted')
    # ### end Alembic commands ###
